merging changes from HEAD branch

diff --git a/src/taxbird-update.sh.in b/src/taxbird-update.sh.in
--- a/src/taxbird-update.sh.in
+++ b/src/taxbird-update.sh.in
@@ -29,7 +29,7 @@ export CVSROOT
 cat <<__FOO
 Pleased to meet you!
 
-This is taxbird-update.sh \$Revision: 1.1 $,
+This is taxbird-update.sh \$Revision: 1.2 $,
 your fully automatic taxbird updater...
 
 __FOO
@@ -69,9 +69,13 @@ if test -e guile/CVS/Repository; then
 
 else
     # we need to do a complete checkout ...
-    $CVS -Qr $CVS_ZFLAG co -d guile -r stable -RP \
+    $CVS -Qr $CVS_ZFLAG co -d guile.new -r stable -RP \
 	taxbird/taxbird/src/guile || \
 	(echo "failed. Sorry."; exit 1)
+
+    # replace old guile sources by fresh ones ...
+    rm -rf guile || (echo "failed. Sorry."; exit 1)
+    mv -f guile.new guile || (echo "failed. Sorry."; exit 1)
 fi
 echo "done."
 
@@ -84,9 +88,13 @@ if test -e pubkeys/CVS/Repository; then
 	(echo "failed. Sorry."; exit 1)
 else
     # we need to do a fresh checkout ...
-    $CVS -Qr $CVS_ZFLAG co -d pubkeys -RP \
+    $CVS -Qr $CVS_ZFLAG co -d pubkeys.new -RP \
 	taxbird/taxbird/src/pubkeys || \
 	(echo "failed. Sorry."; exit 1)
+
+    # replace old pubkeys by new ones ...
+    rm -rf pubkeys  || (echo "failed. Sorry."; exit 1)
+    mv -f pubkeys.new pubkeys  || (echo "failed. Sorry."; exit 1)
 fi
 echo "done."
 
